version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/src/
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/after_install
      timeout: 300
      runas: ubuntu
