# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_url', models.URLField(blank=True, help_text='If page is store-specific, leave iframe URL empty here. You\u2019ll be able to assign this page to the store with specific iframe URL on store edit page.', null=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Pages with higher priority appear first in lists.')),
                ('title', models.CharField(help_text='For example, <tt>View inventory</tt>.', max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
