# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0002_auto_20170624_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Enable group-based access control to this page.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='groups_visible_to',
            field=models.ManyToManyField(help_text='To see this page, store associate must belong to at least one of groups selected. (Region managers can access all pages regardless.)', related_name='pages_visible', to='auth.Group', verbose_name='groups'),
        ),
    ]
