# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zoho', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manager', models.ForeignKey(help_text='Selected user will manage all stores belonging to this region.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manager', models.ForeignKey(help_text='Selected user will manage this store. Note that manager assigned to store\u2019s region will have access as well.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Region')),
            ],
        ),
        migrations.CreateModel(
            name='StorePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_urls', models.TextField(help_text='One store-specific URL per line, no spaces.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_pages', to='zoho.Page')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_pages', to='stores.Store')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='storepage',
            unique_together=set([('page', 'store')]),
        ),
    ]
