# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAssociate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='storepage',
            options={'verbose_name_plural': 'store page contents'},
        ),
        migrations.AlterField(
            model_name='region',
            name='manager',
            field=models.ForeignKey(help_text='Designates one user as region manager having access to all pages of all stores in the region.', on_delete=models.SET(stores.models.get_sentinel_user), related_name='managed_regions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(help_text='Designates one user as store manager having access to all store pages. ', on_delete=models.SET(stores.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='localized store name'),
        ),
        migrations.AlterField(
            model_name='storepage',
            name='iframe_urls',
            field=models.TextField(help_text='At least one store-specific iframe URL, if multiple then each on its own line.', verbose_name='store-level iframe URLs'),
        ),
        migrations.AddField(
            model_name='storeassociate',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associates', to='stores.Store'),
        ),
        migrations.AddField(
            model_name='storeassociate',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(stores.models.get_sentinel_user), related_name='associated_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
