# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAssociate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=models.SET(stores.models.get_sentinel_group), related_name='store_associates', to='auth.Group', verbose_name='belongs to group')),
            ],
        ),
        migrations.AlterModelOptions(
            name='storepage',
            options={'verbose_name_plural': 'store page contents'},
        ),
        migrations.AlterField(
            model_name='region',
            name='manager',
            field=models.ForeignKey(help_text='Designates a user with access to all pages of all stores in this region.', on_delete=models.SET(stores.models.get_sentinel_user), related_name='managed_regions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(help_text='<b>DEPRECATED</b> Add store associate belonging to \u2018store managers\u2019 group instead. One-manager-per-store feature is scheduled for removal. <br>Selected user will manage this store. Note that manager assigned to store\u2019s region will have access as well.', on_delete=models.SET(stores.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storepage',
            name='iframe_urls',
            field=models.TextField(help_text='At least one store-specific iframe URL, if multiple then each on its own line.', verbose_name='store-level iframe URLs'),
        ),
        migrations.AddField(
            model_name='storeassociate',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associates', to='stores.Store'),
        ),
        migrations.AddField(
            model_name='storeassociate',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(stores.models.get_sentinel_user), related_name='associated_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
