# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20170624_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeassociate',
            name='group',
            field=models.ForeignKey(blank=True, help_text='If not specified, user has access to all pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_associates', to='auth.Group', verbose_name='belongs to limited group'),
        ),
    ]
