# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0002_auto_20170624_0830'),
        ('stores', '0003_auto_20170624_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeassociate',
            name='group',
        ),
        migrations.AddField(
            model_name='storeassociate',
            name='pages',
            field=models.ManyToManyField(blank=True, help_text='If not specified, user has access to all pages.', null=True, to='zoho.Page', verbose_name='restricted to areas'),
        ),
    ]
