# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20170624_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeassociate',
            name='pages',
            field=models.ManyToManyField(help_text='If not specified, user has access to all pages.', to='zoho.Page', verbose_name='restricted to areas'),
        ),
    ]
