# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20170624_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeassociate',
            name='pages',
        ),
    ]
