# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_storeassociate_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='manager',
            field=models.ForeignKey(help_text='Designates one user as region manager having access to all pages of all stores in the region.', on_delete=models.SET(stores.models.get_sentinel_user), related_name='managed_regions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(help_text='Designates one user as store manager having access to all store pages. ', on_delete=models.SET(stores.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='localized store name'),
        ),
    ]
